apiVersion: v1
kind: Namespace
metadata:
        name: dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
        name: pipelinedeplo
        namespace: dev
spec:
        replicas: 2
        selector:
                matchLabels:
                        app: webapp
        strategy:
                type: Recreate
        template:
                metadata:
                        name: jenkinspipeline
                        labels:
                                app: webapp
                spec:
                        containers:
                                - name: pipelinecontainer
                                  image: sujanadevops/kubernetes-deployment:1
                                  ports:
                                          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
        name: pipeline-service
        namespace: dev
spec:
         selector:
                 app: webapp
         type: NodePort
         ports:
                 - port: 80
                   targetPort: 8080
                   nodePort: 30033
